### ISSUE TITLE
Usage in an external cluster

### ISSUE THREAD

**Issue by Promaethius** [utilitywarehouse/ingress53#8]
I'm a little confused at how this works but the premise sounds amazing.
Where do I put in my AWS credentials?
Does it watch for new domain names to appear in ingress resources and update route53?
Will it register new domain names?
Will it create entry for subdomains?
Is there an easy way to modify it so that the dns record could use the route53 dns types "weighted, latency, etc." to balance between multiple ingress nodes?

**Comment by alkar** [comment]
@Promaethius thanks for the feedback! We've updated the README file and I think you'll find more answers in there now, regarding setup and configuration.

Right now, it only supports records that are direct subdomains of the zone.

The idea is that you already have a weighted/latency Route53 records pointing to your ingress nodes and that `ingress53` will only create CNAMES to that (the `-target-private` and `-target-public` arguments).

**Comment by alkar** [comment]
Closing this, feel free to raise a new ticket if you have more questions.
